name: Build the source on PR

on: [ pull_request ]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build with Gradle
        uses: gradle/actions/build-action@v3
        with:
          checkout: false
          java-version: 21
          arguments: build